# Pandas Series

# Class No 1(Creation)

In [ ]:
import pandas as pd

In [49]:
firstList = pd.Series([4,8,2,3,6,6,6,])

In [6]:
print(firstList)


0    4
1    8
2    2
3    3
4    6
5    6
6    6
dtype: int64


In [47]:
firstList

0    4
1    8
2    2
3    3
4    6
5    6
6    6
dtype: int64

# Class No 2 (Index)

In [27]:
sales = pd.Series([180,122,1220,362,623362,6236,])

In [28]:
sales.values

array([   180,    122,   1220,    362, 623362,   6236])

In [29]:
sales.index

RangeIndex(start=0, stop=6, step=1)

In [31]:
print(sales.values)
print(sales.index)

[   180    122   1220    362 623362   6236]
RangeIndex(start=0, stop=6, step=1)


In [44]:
saleMth = pd.Series([120,85,1,23,6] , index = ["jan","feb","march","aprtl","maj"])

In [50]:
print(saleMth)

jan      120
feb       85
march      1
aprtl     23
maj        6
dtype: int64


# Class No 3 (Assign Name and values)

In [53]:
print(saleMth.values)
print(saleMth.index)

[120  85   1  23   6]
Index(['jan', 'feb', 'march', 'aprtl', 'maj'], dtype='object')


In [56]:
saleMth_exp_2 = pd.Series([120,85,1,23,6] , index = ["jan","feb","march","aprtl","maj"], name = "This data is not about the whole months")

In [58]:
print(saleMth_exp_2 )

jan      120
feb       85
march      1
aprtl     23
maj        6
Name: This data is not about the whole months, dtype: int64


In [64]:
print(saleMth_exp_2.values) 
print(saleMth_exp_2.index) 
print(saleMth_exp_2.value_counts)

[120  85   1  23   6]
Index(['jan', 'feb', 'march', 'aprtl', 'maj'], dtype='object')
<bound method IndexOpsMixin.value_counts of jan      120
feb       85
march      1
aprtl     23
maj        6
Name: This data is not about the whole months, dtype: int64>


# Class No 4,5,6 (DATA Finding and Allocations)
#<<Set a small Canteen Data for the Practices.>>

In [65]:
string = pd.Series([30,25,33,31,28,26,1],
                   index=['Mondey','Tuesday','Wednesday','Thursday','Firday','Saturday','Sunday'])

In [67]:
string

Mondey       30
Tuesday      25
Wednesday    33
Thursday     31
Firday       28
Saturday     26
Sunday        1
dtype: int64

In [68]:
string


Mondey       30
Tuesday      25
Wednesday    33
Thursday     31
Firday       28
Saturday     26
Sunday        1
dtype: int64

In [81]:
string.value_counts

<bound method IndexOpsMixin.value_counts of Mondey       30
Tuesday      25
Wednesday    33
Thursday     31
Firday       28
Saturday     26
Sunday        1
dtype: int64>

In [ ]:
string = pd.Series([30,25,33,31,28,26,1],
                   index=['Mondey','Tuesday','Wednesday','Thursday','Firday','Saturday','Sunday'])

In [104]:
final_reasult = string[[5,2]]

In [105]:
print(final_reasult)


Saturday     26
Wednesday    33
dtype: int64


In [110]:
print(final_reasult[final_reasult>30])

Wednesday    33
dtype: int64


# Class No 7 (Arathmatic Operations)

In [112]:
string 

Mondey       30
Tuesday      25
Wednesday    33
Thursday     31
Firday       28
Saturday     26
Sunday        1
dtype: int64

In [113]:
string * 2


Mondey       60
Tuesday      50
Wednesday    66
Thursday     62
Firday       56
Saturday     52
Sunday        2
dtype: int64

In [114]:
string +2

Mondey       32
Tuesday      27
Wednesday    35
Thursday     33
Firday       30
Saturday     28
Sunday        3
dtype: int64

# Class No  8,9,10(Panads with Numpy)

In [115]:
import numpy as np


In [117]:
letdata = np.array([9,8,7,4,5,6,3,2,1] )
indexnp = np.array(['a','b','c','d','f','e','f','g','h'])

In [118]:
finalSeries = pd.Series(letdata, index = indexnp) 

In [119]:
print


a    9
b    8
c    7
d    4
f    5
e    6
f    3
g    2
h    1
dtype: int64


In [121]:
"c" in indexnp


True

# Class No 11 (Pandas With dactioniers)

In [124]:
data_in_DIC = {'Punjab' : 12000,'KPK' : 5820,'Sindh' : 8520,'Blochistan': 8421}

In [126]:
taxdata=pd.Series(data_in_DIC)

In [127]:
print(taxdata)

Punjab        12000
KPK            5820
Sindh          8520
Blochistan     8421
dtype: int64


In [129]:
print(taxdata.index)

Index(['Punjab', 'KPK', 'Sindh', 'Blochistan'], dtype='object')


In [130]:
print(taxdata.values)

[12000  5820  8520  8421]


# Class No 12 (Change Order)

In [131]:
data_in_DIC = {'Punjab' : 12000,'KPK' : 5820,'Sindh' : 8520,'Blochistan': 8421}
taxdata=pd.Series(data_in_DIC, index = ['Sindh', 'KPK', 'Punjab', 'Blochistan'])
print(taxdata)

Sindh          8520
KPK            5820
Punjab        12000
Blochistan     8421
dtype: int64


# Class No 13(Null Value Handeling)

In [133]:
data_in_DIC = {'Punjab' : 12000,'KPK' : 5820,'Sindh' : 8520,'Blochistan': 8421}
taxdata=pd.Series(data_in_DIC, index = ['Sindh', 'KPK', 'Punjab', 'Blochistan','GB'])
print(taxdata)    

Sindh          8520.0
KPK            5820.0
Punjab        12000.0
Blochistan     8421.0
GB                NaN
dtype: float64


In [136]:
data_in_DIC = {'Punjab' : 12000,'KPK' : 5820,'Sindh' : 8520,'Blochistan': 8421}
taxdata=pd.Series(data_in_DIC, index = ['Sindh', 'KPK', 'Punjab', 'Blochistan','GB'])
print(taxdata)
print(pd.isnull(taxdata))


Sindh          8520.0
KPK            5820.0
Punjab        12000.0
Blochistan     8421.0
GB                NaN
dtype: float64
Sindh         False
KPK           False
Punjab        False
Blochistan    False
GB             True
dtype: bool


# Class No 14 Last Series_Class(Null Value and name handeling)

In [145]:
taxdata.name="name of Provinces"
taxdata.index.name = "Rupee in Billopns"

In [143]:
print(taxdata)

Rupee in Billopns
Sindh          8520.0
KPK            5820.0
Punjab        12000.0
Blochistan     8421.0
GB                NaN
Name: name of Provinces, dtype: float64
